### ISSUE TITLE
Add support for FLAME

### ISSUE THREAD

**Issue by wavefunction91** [wavefunction91/linalg-cmake-modules#6]
Addresses https://github.com/wavefunction91/GauXC/issues/41

**Comment by wavefunction91** [comment]
@dwdoerf Something tells me that the reason this doesn't work currently is that FLAME doesn't export a completely conformant LAPACK linker - I test for `dpstrf`, so if FLAME doesn't export that symbol, discovery will fail. I'll try to add it to the CI this week and see what happens

**Comment by dwdoerf** [comment]
@wavefunction91 dpstrf seems to be there:

cori02:lib$ pwd
/global/cfs/cdirs/mpccc/dwdoerf/cori-gpu/aocl-linux-gcc/2.2/lib
cori02:lib$ nm libflame.so | grep dpstrf
00000000003bb8b0 T dpstrf_

**Comment by wavefunction91** [comment]
Fixed in https://github.com/wavefunction91/linalg-cmake-modules/pull/1/commits/00b0cdd82663346ae5e400ab921e43468f307678
